apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - demo.questdev.xyz
    secretName: {{ template "helm-guestbook.fullname" . }}-tls
  rules:
  - host: demo.questdev.xyz
    http:
      paths:
      - path: /
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ template "helm-guestbook.fullname" . }}
          servicePort: 80
