apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo.questdev.xyz
    http:
      paths:
      - path: /
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ template "helm-guestbook.fullname" . }}
          servicePort: 80
